spring:
  application:
    name: coinmarketcap
  config:
    import: vault://
  cloud:
    vault:
      generic:
        enabled: true
        default-context: credentials
        backend: coinmarketcap
      uri: http://127.0.0.1:8200
      token: ${vault.token}
      scheme: http
      kv:
        enabled: true
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml

server:
  port: 8095
  servlet:
    context-path: /${spring.application.name}

