spring:
  application:
    name: coinmarketcap
  config:
    import: vault://
  cloud:
    vault:
      generic:
        enabled: true
        default-context: credentials
        backend: coinmarketcap
      uri: http://127.0.0.1:8200
      token: ${vault.token}
      scheme: http
      kv:
        enabled: true
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      #30 seconds
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 10
      #10 minutes
      idle-timeout: 600000
      #30 minutes
      max-lifetime: 1800000
      auto-commit: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml

server:
  port: 8095
  servlet:
    context-path: /${spring.application.name}

coinmarketcap:
  api:
    host:
      baseurl: https://pro-api.coinmarketcap.com/v1/cryptocurrency/
  url:
    listings: listings/latest?CMC_PRO_API_KEY={token}
    quotes: quotes/latest?CMC_PRO_API_KEY={token}&symbol={symbol}&convert=USD
  token: ${coinmarketcap.token}

