spring:
  application:
    name: finance
  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token: ${vault.token}
      scheme: http
      kv:
        backend-version: 2
        enabled: true
        backend: kv
        application-name: finance/db,finance/coinmarketcap,finance/fixer, finance/polygon
        profile-separator: '/'
        default-context: finance/db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://66fd-45-159-74-79.ngrok-free.app/realms/SpringCryptoKeycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      #30 seconds
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 10
      #10 minutes
      idle-timeout: 600000
      #30 minutes
      max-lifetime: 1800000
      auto-commit: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml

jwt:
  auth:
    converter:
      resource-id: springboot-keycloak-client
      principal-attribute: preferred_username


server:
  port: 8095
  servlet:
    context-path: /${spring.application.name}

app:
  cors:
    allowed-origins: http://localhost:3000, https://66fd-45-159-74-79.ngrok-free.app


coinmarketcap:
  api:
    host:
      baseurl: https://pro-api.coinmarketcap.com/v1/cryptocurrency/
  url:
    listings: listings/latest?CMC_PRO_API_KEY={token}
    quotes: quotes/latest?CMC_PRO_API_KEY={token}&symbol={symbol}&convert=USD
  token: ${coinmarketcap.token}

fixer:
  api:
    host:
      baseurl: http://data.fixer.io/api/
  url:
    latest-currencies: latest?access_key={token}
  token: ${fixer.token}

polygon:
  api:
    host:
      baseurl:  https://api.polygon.io/v2/
  url:
    get-on-date:  locale/us/market/stocks/{date}?adjusted=true&apikey={token}
  token: ${polygon.token}

currency-freaks:
  api:
    host:
      baseurl:  https://api.polygon.io/v2/
  url:
    get-on-date:  locale/us/market/stocks/{date}?adjusted=true&apikey={token}
  token: ${polygon.token}

