INSERT INTO sp500 (symbol, name, sector) VALUES ('MMM', '3M Company', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AOS', 'A.O. Smith Corp', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ABT', 'Abbott Laboratories', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ABBV', 'AbbVie Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ABMD', 'ABIOMED Inc', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ACN', 'Accenture plc', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ATVI', 'Activision Blizzard', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ADBE', 'Adobe Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AAP', 'Advance Auto Parts', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AMD', 'Advanced Micro Devices Inc', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AES', 'AES Corp', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AFL', 'AFLAC Inc', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('A', 'Agilent Technologies Inc', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('APD', 'Air Products & Chemicals Inc', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AKAM', 'Akamai Technologies Inc', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ALK', 'Alaska Air Group Inc', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ALB', 'Albemarle Corp', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ARE', 'Alexandria Real Estate Equities', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ALXN', 'Alexion Pharmaceuticals', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ALGN', 'Align Technology', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ALLE', 'Allegion', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LNT', 'Alliant Energy Corp', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ALL', 'Allstate Corp', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GOOGL', 'Alphabet Inc. (Class A)', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GOOG', 'Alphabet Inc. (Class C)', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MO', 'Altria Group Inc', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AMZN', 'Amazon.com Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AMCR', 'Amcor plc', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AEE', 'Ameren Corp', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AAL', 'American Airlines Group', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AEP', 'American Electric Power', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AXP', 'American Express Co', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AIG', 'American International Group', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AMT', 'American Tower Corp.', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AWK', 'American Water Works Company Inc', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AMP', 'Ameriprise Financial', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ABC', 'AmerisourceBergen Corp', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AME', 'AMETEK Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AMGN', 'Amgen Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('APH', 'Amphenol Corp', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ADI', 'Analog Devices Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ANSS', 'ANSYS', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ANTM', 'Anthem', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AON', 'Aon plc', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('APA', 'Apache Corporation', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AIV', 'Apartment Investment & Management', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AAPL', 'Apple Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AMAT', 'Applied Materials Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('APTV', 'Aptiv PLC', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ADM', 'Archer-Daniels-Midland Co', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ANET', 'Arista Networks', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AJG', 'Arthur J. Gallagher & Co.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AIZ', 'Assurant', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('T', 'AT&T Inc.', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ATO', 'Atmos Energy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ADSK', 'Autodesk Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ADP', 'Automatic Data Processing', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AZO', 'AutoZone Inc', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AVB', 'AvalonBay Communities', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AVY', 'Avery Dennison Corp', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BKR', 'Baker Hughes Co', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BLL', 'Ball Corp', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BAC', 'Bank of America Corp', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BAX', 'Baxter International Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BDX', 'Becton Dickinson', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BRK.B', 'Berkshire Hathaway', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BBY', 'Best Buy Co. Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BIO', 'Bio-Rad Laboratories', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BIIB', 'Biogen Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BLK', 'BlackRock', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BA', 'Boeing Company', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BKNG', 'Booking Holdings Inc', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BWA', 'BorgWarner', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BXP', 'Boston Properties', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BSX', 'Boston Scientific', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BMY', 'Bristol-Myers Squibb', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('AVGO', 'Broadcom Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BR', 'Broadridge Financial Solutions', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BF.B', 'Brown-Forman Corp.', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CHRW', 'C. H. Robinson Worldwide', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('COG', 'Cabot Oil & Gas', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CDNS', 'Cadence Design Systems', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CPB', 'Campbell Soup', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('COF', 'Capital One Financial', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CAH', 'Cardinal Health Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KMX', 'Carmax Inc', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CCL', 'Carnival Corp.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CARR', 'Carrier Global', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CAT', 'Caterpillar Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CBOE', 'Cboe Global Markets', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CBRE', 'CBRE Group', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CDW', 'CDW', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CE', 'Celanese', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CNC', 'Centene Corporation', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CNP', 'CenterPoint Energy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CTL', 'CenturyLink Inc', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CERN', 'Cerner', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CF', 'CF Industries Holdings Inc', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SCHW', 'Charles Schwab Corporation', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CHTR', 'Charter Communications', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CVX', 'Chevron Corp.', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CMG', 'Chipotle Mexican Grill', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CB', 'Chubb Limited', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CHD', 'Church & Dwight', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CI', 'CIGNA Corp.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CINF', 'Cincinnati Financial', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CTAS', 'Cintas Corporation', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CSCO', 'Cisco Systems', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('C', 'Citigroup Inc.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CFG', 'Citizens Financial Group', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CTXS', 'Citrix Systems', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CME', 'CME Group Inc.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CMS', 'CMS Energy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KO', 'Coca-Cola Company', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CTSH', 'Cognizant Technology Solutions', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CL', 'Colgate-Palmolive', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CMCSA', 'Comcast Corp.', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CMA', 'Comerica Inc.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CAG', 'Conagra Brands', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CXO', 'Concho Resources', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('COP', 'ConocoPhillips', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ED', 'Consolidated Edison', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('STZ', 'Constellation Brands', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CPRT', 'Copart Inc', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GLW', 'Corning Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CTVA', 'Corteva', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('COST', 'Costco Wholesale Corp.', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('COTY', 'Coty Inc', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CCI', 'Crown Castle International Corp.', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CSX', 'CSX Corp.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CMI', 'Cummins Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CVS', 'CVS Health', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DHI', 'D. R. Horton', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DHR', 'Danaher Corp.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DRI', 'Darden Restaurants', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DVA', 'DaVita Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DE', 'Deere & Co.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DAL', 'Delta Air Lines Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('XRAY', 'Dentsply Sirona', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DVN', 'Devon Energy', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DXCM', 'DexCom', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FANG', 'Diamondback Energy', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DLR', 'Digital Realty Trust Inc', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DFS', 'Discover Financial Services', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DISCA', 'Discovery Inc. (Class A)', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DISCK', 'Discovery Inc. (Class C)', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DISH', 'Dish Network', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DG', 'Dollar General', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DLTR', 'Dollar Tree', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('D', 'Dominion Energy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DPZ', 'Dominos Pizza', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DOV', 'Dover Corporation', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DOW', 'Dow Inc.', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DTE', 'DTE Energy Co.', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DUK', 'Duke Energy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DRE', 'Duke Realty Corp', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DD', 'DuPont de Nemours Inc', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DXC', 'DXC Technology', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ETFC', 'E*Trade', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EMN', 'Eastman Chemical', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ETN', 'Eaton Corporation', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EBAY', 'eBay Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ECL', 'Ecolab Inc.', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EIX', 'Edison Intl', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EW', 'Edwards Lifesciences', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EA', 'Electronic Arts', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EMR', 'Emerson Electric Company', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ETR', 'Entergy Corp.', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EOG', 'EOG Resources', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EFX', 'Equifax Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EQIX', 'Equinix', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EQR', 'Equity Residential', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ESS', 'Essex Property Trust Inc.', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EL', 'Estée Lauder Companies', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('RE', 'Everest Re Group Ltd.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EVRG', 'Evergy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ES', 'Eversource Energy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EXC', 'Exelon Corp.', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EXPE', 'Expedia Group', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EXPD', 'Expeditors', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('EXR', 'Extra Space Storage', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('XOM', 'Exxon Mobil Corp.', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FFIV', 'F5 Networks', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FB', 'Facebook Inc.', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FAST', 'Fastenal Co', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FRT', 'Federal Realty Investment Trust', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FDX', 'FedEx Corporation', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FIS', 'Fidelity National Information Services', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FITB', 'Fifth Third Bancorp', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FRC', 'First Republic Bank', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FE', 'FirstEnergy Corp', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FISV', 'Fiserv Inc', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FLT', 'FleetCor Technologies Inc', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FLIR', 'FLIR Systems', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FLS', 'Flowserve Corporation', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FMC', 'FMC Corporation', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('F', 'Ford Motor Company', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FTNT', 'Fortinet', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FTV', 'Fortive Corp', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FBHS', 'Fortune Brands Home & Security', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FOXA', 'Fox Corporation (Class A)', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FOX', 'Fox Corporation (Class B)', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BEN', 'Franklin Resources', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FCX', 'Freeport-McMoRan Inc.', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GPS', 'Gap Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GRMN', 'Garmin Ltd.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IT', 'Gartner Inc', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GD', 'General Dynamics', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GE', 'General Electric', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GIS', 'General Mills', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GM', 'General Motors', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GPC', 'Genuine Parts', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GILD', 'Gilead Sciences', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GPN', 'Global Payments Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GL', 'Globe Life Inc.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GS', 'Goldman Sachs Group', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('GWW', 'Grainger (W.W.) Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HRB', 'H&R Block', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HAL', 'Halliburton Co.', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HBI', 'Hanesbrands Inc', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HIG', 'Hartford Financial Svc.Gp.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HAS', 'Hasbro Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HCA', 'HCA Healthcare', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PEAK', 'Healthpeak Properties', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HSIC', 'Henry Schein', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HES', 'Hess Corporation', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HPE', 'Hewlett Packard Enterprise', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HLT', 'Hilton Worldwide Holdings Inc', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HFC', 'HollyFrontier Corp', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HOLX', 'Hologic', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HD', 'Home Depot', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HON', 'Honeywell Intl Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HRL', 'Hormel Foods Corp.', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HST', 'Host Hotels & Resorts', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HWM', 'Howmet Aerospace', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HPQ', 'HP Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HUM', 'Humana Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HBAN', 'Huntington Bancshares', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HII', 'Huntington Ingalls Industries', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IEX', 'IDEX Corporation', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IDXX', 'IDEXX Laboratories', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('INFO', 'IHS Markit Ltd.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ITW', 'Illinois Tool Works', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ILMN', 'Illumina Inc', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('INCY', 'Incyte', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IR', 'Ingersoll Rand', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('INTC', 'Intel Corp.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ICE', 'Intercontinental Exchange', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IBM', 'International Business Machines', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IFF', 'International Flavors & Fragrances', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IP', 'International Paper', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IPG', 'Interpublic Group', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('INTU', 'Intuit Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ISRG', 'Intuitive Surgical Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IVZ', 'Invesco Ltd.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IPGP', 'IPG Photonics Corp.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IQV', 'IQVIA Holdings Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('IRM', 'Iron Mountain Incorporated', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('JBHT', 'J. B. Hunt Transport Services', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('JKHY', 'Jack Henry & Associates', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('J', 'Jacobs Engineering Group', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SJM', 'JM Smucker', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('JNJ', 'Johnson & Johnson', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('JCI', 'Johnson Controls International', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('JPM', 'JPMorgan Chase & Co.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('JNPR', 'Juniper Networks', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KSU', 'Kansas City Southern', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('K', 'Kellogg Co.', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KEY', 'KeyCorp', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KEYS', 'Keysight Technologies', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KMB', 'Kimberly-Clark', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KIM', 'Kimco Realty', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KMI', 'Kinder Morgan', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KLAC', 'KLA Corporation', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KSS', 'Kohls Corp.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KHC', 'Kraft Heinz Co', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('KR', 'Kroger Co.', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LB', 'L Brands Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LHX', 'L3Harris Technologies', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LH', 'Laboratory Corp. of America Holding', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LRCX', 'Lam Research', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LW', 'Lamb Weston Holdings Inc', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LVS', 'Las Vegas Sands', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LEG', 'Leggett & Platt', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LDOS', 'Leidos Holdings', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LEN', 'Lennar Corp.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LLY', 'Lilly (Eli) & Co.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LNC', 'Lincoln National', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LIN', 'Linde plc', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LYV', 'Live Nation Entertainment', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LKQ', 'LKQ Corporation', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LMT', 'Lockheed Martin Corp.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('L', 'Loews Corp.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LOW', 'Lowes Cos.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LYB', 'LyondellBasell', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MTB', 'M&T Bank Corp.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MRO', 'Marathon Oil Corp.', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MPC', 'Marathon Petroleum', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MKTX', 'MarketAxess', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MAR', 'Marriott Intl.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MMC', 'Marsh & McLennan', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MLM', 'Martin Marietta Materials', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MAS', 'Masco Corp.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MA', 'Mastercard Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MXIM', 'Maxim Integrated Products Inc', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MKC', 'McCormick & Co.', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MCD', 'McDonalds Corp.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MCK', 'McKesson Corp.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MDT', 'Medtronic plc', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MRK', 'Merck & Co.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MET', 'MetLife Inc.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MTD', 'Mettler Toledo', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MGM', 'MGM Resorts International', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MCHP', 'Microchip Technology', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MU', 'Micron Technology', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MSFT', 'Microsoft Corp.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MAA', 'Mid-America Apartments', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MHK', 'Mohawk Industries', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TAP', 'Molson Coors Beverage Company', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MDLZ', 'Mondelez International', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MNST', 'Monster Beverage', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MCO', 'Moodys Corp', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MS', 'Morgan Stanley', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MSI', 'Motorola Solutions Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MSCI', 'MSCI Inc', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MYL', 'Mylan N.V.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NDAQ', 'Nasdaq Inc.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NOV', 'National Oilwell Varco Inc.', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NTAP', 'NetApp', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NFLX', 'Netflix Inc.', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NWL', 'Newell Brands', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NEM', 'Newmont Corporation', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NWSA', 'News Corp. Class A', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NWS', 'News Corp. Class B', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NEE', 'NextEra Energy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NLSN', 'Nielsen Holdings', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NKE', 'Nike Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NI', 'NiSource Inc.', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NBL', 'Noble Energy', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NSC', 'Norfolk Southern Corp.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NTRS', 'Northern Trust Corp.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NOC', 'Northrop Grumman', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NLOK', 'NortonLifeLock', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NCLH', 'Norwegian Cruise Line Holdings', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NRG', 'NRG Energy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NUE', 'Nucor Corp.', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NVDA', 'Nvidia Corporation', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NVR', 'NVR Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ORLY', 'OReilly Automotive', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('OXY', 'Occidental Petroleum', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ODFL', 'Old Dominion Freight Line', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('OMC', 'Omnicom Group', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('OKE', 'ONEOK', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ORCL', 'Oracle Corp.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('OTIS', 'Otis Worldwide', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PCAR', 'PACCAR Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PKG', 'Packaging Corporation of America', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PH', 'Parker-Hannifin', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PAYX', 'Paychex Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PAYC', 'Paycom', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PYPL', 'PayPal', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PNR', 'Pentair plc', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PBCT', 'Peoples United Financial', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PEP', 'PepsiCo Inc.', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PKI', 'PerkinElmer', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PRGO', 'Perrigo', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PFE', 'Pfizer Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PM', 'Philip Morris International', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PSX', 'Phillips 66', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PNW', 'Pinnacle West Capital', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PXD', 'Pioneer Natural Resources', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PNC', 'PNC Financial Services', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PPG', 'PPG Industries', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PPL', 'PPL Corp.', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PFG', 'Principal Financial Group', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PG', 'Procter & Gamble', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PGR', 'Progressive Corp.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PLD', 'Prologis', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PRU', 'Prudential Financial', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PEG', 'Public Service Enterprise Group (PSEG)', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PSA', 'Public Storage', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PHM', 'PulteGroup', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PVH', 'PVH Corp.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('QRVO', 'Qorvo', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('QCOM', 'QUALCOMM Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('PWR', 'Quanta Services Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DGX', 'Quest Diagnostics', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('RL', 'Ralph Lauren Corporation', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('RJF', 'Raymond James Financial Inc.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('RTX', 'Raytheon Technologies', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('O', 'Realty Income Corporation', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('REG', 'Regency Centers Corporation', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('REGN', 'Regeneron Pharmaceuticals', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('RF', 'Regions Financial Corp.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('RSG', 'Republic Services Inc', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('RMD', 'ResMed', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('RHI', 'Robert Half International', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ROK', 'Rockwell Automation Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ROL', 'Rollins Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ROP', 'Roper Technologies', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ROST', 'Ross Stores', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('RCL', 'Royal Caribbean Group', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SPGI', 'S&P Global Inc.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CRM', 'Salesforce.com', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SBAC', 'SBA Communications', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SLB', 'Schlumberger Ltd.', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('STX', 'Seagate Technology', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SEE', 'Sealed Air', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SRE', 'Sempra Energy', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('NOW', 'ServiceNow', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SHW', 'Sherwin-Williams', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SPG', 'Simon Property Group Inc', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SWKS', 'Skyworks Solutions', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SLG', 'SL Green Realty', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SNA', 'Snap-on', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SO', 'Southern Company', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('LUV', 'Southwest Airlines', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SWK', 'Stanley Black & Decker', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SBUX', 'Starbucks Corp.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('STT', 'State Street Corp.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('STE', 'STERIS plc', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SYK', 'Stryker Corp.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SIVB', 'SVB Financial', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SYF', 'Synchrony Financial', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SNPS', 'Synopsys Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('SYY', 'Sysco Corp.', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TMUS', 'T-Mobile US', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TROW', 'T. Rowe Price Group', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TTWO', 'Take-Two Interactive', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TPR', 'Tapestry Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TGT', 'Target Corp.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TEL', 'TE Connectivity Ltd.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('FTI', 'TechnipFMC', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TDY', 'Teledyne Technologies', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TFX', 'Teleflex', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TXN', 'Texas Instruments', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TXT', 'Textron Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('BK', 'The Bank of New York Mellon', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('CLX', 'The Clorox Company', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('COO', 'The Cooper Companies', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('HSY', 'The Hershey Company', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('MOS', 'The Mosaic Company', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TRV', 'The Travelers Companies Inc.', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('DIS', 'The Walt Disney Company', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TMO', 'Thermo Fisher Scientific', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TIF', 'Tiffany & Co.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TJX', 'TJX Companies Inc.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TSCO', 'Tractor Supply Company', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TT', 'Trane Technologies plc', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TDG', 'TransDigm Group', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TFC', 'Truist Financial', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TWTR', 'Twitter Inc.', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TYL', 'Tyler Technologies', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('TSN', 'Tyson Foods', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('USB', 'U.S. Bancorp', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('UDR', 'UDR Inc.', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ULTA', 'Ulta Beauty', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('UAA', 'Under Armour (Class A)', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('UA', 'Under Armour (Class C)', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('UNP', 'Union Pacific Corp', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('UAL', 'United Airlines Holdings', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('UNH', 'United Health Group Inc.', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('UPS', 'United Parcel Service', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('URI', 'United Rentals Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('UHS', 'Universal Health Services', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('UNM', 'Unum Group', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VLO', 'Valero Energy', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VAR', 'Varian Medical Systems', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VTR', 'Ventas Inc', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VRSN', 'Verisign Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VRSK', 'Verisk Analytics', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VZ', 'Verizon Communications', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VRTX', 'Vertex Pharmaceuticals Inc', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VFC', 'VF Corporation', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VIAC', 'ViacomCBS', 'Communication Services');
INSERT INTO sp500 (symbol, name, sector) VALUES ('V', 'Visa Inc.', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VNO', 'Vornado Realty Trust', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('VMC', 'Vulcan Materials', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WRB', 'W. R. Berkley Corporation', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WAB', 'Wabtec Corporation', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WBA', 'Walgreens Boots Alliance', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WMT', 'Walmart', 'Consumer Staples');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WM', 'Waste Management Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WAT', 'Waters Corporation', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WEC', 'WEC Energy Group', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WFC', 'Wells Fargo', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WELL', 'Welltower Inc.', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WST', 'West Pharmaceutical Services', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WDC', 'Western Digital', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WU', 'Western Union Co', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WRK', 'WestRock', 'Materials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WY', 'Weyerhaeuser', 'Real Estate');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WHR', 'Whirlpool Corp.', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WMB', 'Williams Companies', 'Energy');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WLTW', 'Willis Towers Watson', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('WYNN', 'Wynn Resorts Ltd', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('XEL', 'Xcel Energy Inc', 'Utilities');
INSERT INTO sp500 (symbol, name, sector) VALUES ('XRX', 'Xerox', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('XLNX', 'Xilinx', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('XYL', 'Xylem Inc.', 'Industrials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('YUM', 'Yum! Brands Inc', 'Consumer Discretionary');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ZBRA', 'Zebra Technologies', 'Information Technology');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ZBH', 'Zimmer Biomet Holdings', 'Health Care');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ZION', 'Zions Bancorp', 'Financials');
INSERT INTO sp500 (symbol, name, sector) VALUES ('ZTS', 'Zoetis', 'Health Care');