INSERT INTO currency (name, description) VALUES
('AGLD', 'Adventure Gold'),
('FJD', 'Fiji Dollar'),
('MXN', 'Mexican Peso'),
('LVL', 'Latvian Lats'),
('SCR', 'Seychellois Rupee'),
('CDF', 'Congolese Franc'),
('BBD', 'Barbadian Dollar'),
('HNL', 'Honduran Lempira'),
('UGX', 'Uganda Shilling'),
('GLM', 'Golem'),
('NEAR', 'NEAR Protocol'),
('AIOZ', 'Aioz Network'),
('AUDIO', 'Audius'),
('FARM', 'Harvest Finance'),
('SDG', 'Sudanese Pound'),
('IQD', 'Iraqi Dinar'),
('GMD', 'Gambian Dalasi'),
('RBN', 'Ribbon Finance'),
('ZRX', 'ZRX 0x'),
('BCH', 'Bitcoin Cash'),
('MYR', 'Malaysian Ringgit'),
('FKP', 'Falkland Islands Pound'),
('XOF', 'West African CFA Franc'),
('GMT', 'Stepn'),
('SEK', 'Swedish Krona'),
('GNF', 'Guinean Franc'),
('MZN', 'Mozambican Metical'),
('QAR', 'Qatari Rial'),
('IRR', 'Iranian Rial'),
('GNO', 'Gnosis'),
('GNT', 'GreenTrust'),
('FLR', 'FLARE'),
('XPD', 'Palladium'),
('THB', 'Thai Baht'),
('XPF', 'CFP Franc'),
('ABT', 'Arcblock'),
('BDT', 'Bangladeshi Taka'),
('T', 'Threshold'),
('LYD', 'Libyan Dinar'),
('KWD', 'Kuwaiti Dinar'),
('DIA', 'Dia'),
('XPT', 'Platinum'),
('ISK', 'Iceland Krona'),
('JUP', 'Jupiter'),
('ACH', 'Alchemy Pay'),
('MINA', 'Mina'),
('PAB', 'Panamanian Balboa'),
('ACS', 'ACryptoS'),
('SGD', 'Singapore Dollar'),
('BLUR', 'Blur'),
('REN', 'renBTC'),
('ELA', 'Elastos'),
('REP', 'Augur'),
('ADA', 'Cardano'),
('REQ', 'Request'),
('STORJ', 'Storj'),
('CHF', 'Swiss Franc'),
('HRK', 'Croatian Kuna'),
('RARI', 'Rarible'),
('DJF', 'Djibouti Franc'),
('RARE', 'SuperRare'),
('PAX', 'Paxos Standard Token'),
('VND', 'Vietnamese Dong'),
('CHZ', 'Chiliz'),
('KYD', 'Cayman Islands Dollar'),
('XRP', 'Ripple'),
('JASMY', 'Jasmy'),
('SHP', 'Saint Helena Pound'),
('INDEX', 'Index Cooperative'),
('TJS', 'Tajikistani Somoni'),
('AED', 'UAE Dirham'),
('FIDA', 'Bonfida'),
('SAND', 'The Sandbox'),
('DKK', 'Danish Krone'),
('WCFG', 'Wrapped Centrifuge'),
('ZWD', 'Zimbabwean Dollar'),
('OCEAN', 'Ocean Protocol'),
('BGN', 'Bulgarian Lev'),
('UMA', 'Universal Market Access'),
('FOX', 'Shapeshift FOX Token'),
('ZWL', 'Zimbabwean Dollar'),
('HTG', 'Haitian Gourde'),
('RGT', 'Rari Governance Token'),
('BHD', 'Bahraini Dinar'),
('ENJ', 'Enjin Coin'),
('COVAL', 'COVAL'),
('CGLD', 'Celo Gold'),
('KZT', 'Kazakhstani Tenge'),
('YFII', 'DFI.Money'),
('DIMO', 'DIMO'),
('GRT', 'The Graph'),
('AFN', 'Afghan Afghani'),
('ENS', 'Ethereum Name Service'),
('UNI', 'Uniswap'),
('FX', 'Function X'),
('XTS', 'Xaviera Techno Solutions'),
('HUF', 'Hungarian Forint'),
('BIF', 'Burundian Franc'),
('XTZ', 'Tezos'),
('AURORA', 'Aurora'),
('EOS', 'EOS'),
('GST', 'Green Satoshi Token'),
('FORT', 'Forta'),
('SWFTC', 'SwftCoin'),
('BIT', 'BitDAO'),
('NAD', 'Namibian Dollar'),
('SKK', 'Slovak Koruna'),
('SKL', 'SKALE Network'),
('TMM', 'Turkmenistan Manat'),
('GTC', 'Gitcoin'),
('PEN', 'Peruvian Sol'),
('WST', 'Samoan Tālā'),
('SHPING', 'Shping Coin'),
('TMT', 'Turkmenistani Manat'),
('CLF', 'Chilean Unit of Account (UF)'),
('EUROC', 'Euro Coin'),
('GTQ', 'Guatemalan Quetzal'),
('CLP', 'Chilean Peso'),
('DNT', 'District0x'),
('TND', 'Tunisian Dinar'),
('CLV', 'Clover Finance'),
('SLE', 'Sierra Leonean Leone'),
('FLOW', 'Flow'),
('UPI', 'Pawtocol'),
('SLL', 'Sierra Leonean Leone'),
('DOP', 'Dominican Peso'),
('DOT', 'Polkadot'),
('1INCH', '1inch'),
('MAD', 'Moroccan Dirham'),
('TOP', 'Tongan Paʻanga'),
('PGK', 'Papua New Guinean Kina'),
('GYEN', 'GYEN'),
('UNFI', 'Unifi Protocol DAO'),
('CNH', 'Chinese Yuan Renminbi Offshore'),
('NCT', 'Polyswarm'),
('WLUNA', 'Wrapped LUNA'),
('POWR', 'Powerledger'),
('ERN', 'Eritrean Nakfa'),
('VOXEL', 'Voxies'),
('RLC', 'iExec RLC'),
('CNY', 'Chinese Yuan Renminbi'),
('ATOM', 'Cosmos'),
('QUICK', 'QuickSwap'),
('BLZ', 'Bluzelle'),
('BOBA', 'Boba Network'),
('TONE', 'TE-FOOD'),
('BMD', 'Bermudian Dollar'),
('SNT', 'Status Network'),
('PHP', 'Philippine Piso'),
('SNX', 'Synthetix Network'),
('RLY', 'Rally'),
('COP', 'Colombian Peso'),
('USD', 'US Dollar'),
('API3', 'API3'),
('HOPR', 'HOPR'),
('ROSE', 'Oasis Network'),
('XYO', 'XYO Network'),
('SOL', 'Solana'),
('ETB', 'Ethiopian Birr'),
('ETC', 'Ethereum Classic'),
('SOS', 'Somali Shilling'),
('VUV', 'Vanuatu Vatu'),
('LAK', 'Laotian Kip'),
('OGN', 'Origin Token'),
('UST', 'TerraUSD'),
('CELR', 'Celer Network'),
('ETH', 'Ethereum'),
('BND', 'Brunei Dollar'),
('AUCTION', 'Bounce Token AUCTION'),
('BADGER', 'Badger DAO'),
('MULTI', 'Multichain'),
('ALL', 'Albanian Lek'),
('HIGH', 'Highstreet'),
('SPA', 'Sperax'),
('TRB', 'Tellor'),
('BNT', 'Bancor Network'),
('GYD', 'Guyana Dollar'),
('BOB', 'Bolivian Boliviano'),
('MDL', 'Moldovan Leu'),
('TRU', 'TrueFi'),
('AMD', 'Armenian Dram'),
('DREP', 'Drep [new]'),
('TRY', 'Turkish Lira'),
('LBP', 'Lebanese Pound'),
('MDT', 'Measurable Data Token'),
('AERGO', 'Aergo'),
('EUR', 'Euro'),
('AMP', 'Amp'),
('ORCA', 'Orca'),
('RON', 'Romanian Leu'),
('NGN', 'Nigerian Naira'),
('CRC', 'Costa Rican Colon'),
('PKR', 'Pakistani Rupee'),
('ANG', 'Netherlands Antillean Guilder'),
('EGLD', 'Elrond'),
('SPELL', 'Spell Token'),
('PUNDIX', 'Pundi X (New)'),
('LCX', 'LCX'),
('CRO', 'Crypto.com Chain'),
('PLA', 'PlayDapp'),
('SRD', 'Surinamese Dollar'),
('TTD', 'Trinidad and Tobago Dollar'),
('CRV', 'Curve DAO Token'),
('MNDE', 'Marinade'),
('NU', 'NuCypher'),
('ANT', 'Aragon'),
('RPL', 'Rocket Pool'),
('AOA', 'Angolan Kwanza'),
('PLN', 'Polish Zloty'),
('LDO', 'Lido DAO Token'),
('QNT', 'Quant'),
('MAGIC', 'MAGIC'),
('ALICE', 'My Neighbor Alice'),
('PLU', 'Pluton'),
('MUSD', 'mStableUSD'),
('MUSE', 'Muse'),
('OP', 'Optimism'),
('MGA', 'Malagasy Ariary'),
('SSP', 'South Sudanese Pound'),
('NIO', 'Nicaraguan Córdoba'),
('APE', 'ApeCoin'),
('ETH2', 'Ethereum 2.0'),
('BUSD', 'Binance USD'),
('ARPA', 'ARPA Chain'),
('BRL', 'Brazilian Real'),
('MCO2', 'Moss Carbon Credit'),
('ALCX', 'Alchemix'),
('00', '00 Token'),
('MATIC', 'Polygon'),
('STD', 'São Tomé and Príncipe Dobra'),
('APT', 'Aptos'),
('CTX', 'Cryptex Finance'),
('STG', 'Stargate Finance'),
('PNG', 'Pangolin'),
('TVK', 'Terra Virtua Kolect'),
('IOTX', 'IoTeX'),
('SHIB', 'Shiba Inu'),
('ZAR', 'South African Rand'),
('STN', 'São Tomé and Príncipe Dobra'),
('CUC', 'Cuban Convertible Peso'),
('BSD', 'Bahamian Dollar'),
('STX', 'Stacks'),
('QI', 'BENQI'),
('CUP', 'Cuban Peso'),
('TWD', 'New Taiwan Dollar'),
('RSD', 'Serbian Dinar'),
('BSV', 'Bitcoin SV'),
('SUI', 'Sui'),
('MSOL', 'Marinade Staked SOL'),
('OMG', 'Omisego'),
('BAND', 'Band Protocol'),
('BTC', 'Bitcoin'),
('NKN', 'NKN'),
('UYU', 'Uruguayan Peso'),
('ARB', 'Arbitrum'),
('CVC', 'Civic'),
('CVE', 'Cape Verdean Escudo'),
('OMR', 'Omani Rial'),
('MIR', 'Mirror Protocol'),
('KES', 'Kenyan Shilling'),
('LOKA', 'League of Kingdoms Arena'),
('BTN', 'Bhutanese Ngultrum'),
('SVC', 'Salvadoran Colón'),
('ARS', 'Argentine Peso'),
('CVX', 'Convex Finance'),
('ANKR', 'Ankr Network'),
('SUSHI', 'SushiSwap'),
('ALGO', 'Algorand'),
('SYLO', 'Sylo'),
('UZS', 'Uzbekistani Som'),
('WBTC', 'Wrapped Bitcoin'),
('DYP', 'DeFi Yield Protocol'),
('ASM', 'Assemble Protocol'),
('RUB', 'Russian Ruble'),
('AST', 'AirSwap'),
('MANA', 'Mana Coin Decentraland'),
('MKD', 'Macedonian Denar'),
('ATA', 'Automata Network'),
('DZD', 'Algerian Dinar'),
('QSP', 'Quantstamp'),
('NMR', 'Numeraire Network'),
('JEP', 'Jersey Pound'),
('MKR', 'Maker'),
('KGS', 'Kyrgyzstani Som'),
('LIT', 'Litentry'),
('ICP', 'Internet Computer'),
('ZEC', 'ZCash'),
('XAF', 'Central African CFA franc'),
('NEST', 'NEST Protocol'),
('XAG', 'Silver (troy ounce)'),
('ZEN', 'Horizen'),
('DESO', 'Decentralized Social'),
('LOOM', 'Loom Network'),
('DOGE', 'Dogecoin'),
('HBAR', 'Hedera'),
('PRO', 'Propy'),
('TZS', 'Tanzanian Shilling'),
('XAU', 'Gold (troy ounce)'),
('MLN', 'Enzyme'),
('PRQ', 'PARSIQ'),
('AUD', 'Australian Dollar'),
('KHR', 'Cambodian Riel'),
('IDR', 'Indonesian Rupiah'),
('XBA', 'XBank'),
('CTSI', 'Cartesi'),
('BWP', 'Botswanan Pula'),
('RWF', 'Rwandan Franc'),
('KAVA', 'Kava'),
('C98', 'Coin98'),
('SYN', 'Synapse'),
('MMK', 'Burmese Kyat'),
('NOK', 'Norwegian Krone'),
('SYP', 'Syrian Pound'),
('CRPT', 'Crypterium'),
('LKR', 'Sri Lankan Rupee'),
('GAL', 'Project Galaxy'),
('CZK', 'Czech Koruna'),
('XCD', 'East Caribbean Dollar'),
('AVT', 'Aventus'),
('XCN', 'Chain'),
('SZL', 'Swazi Lilangeni'),
('YER', 'Yemeni Rial'),
('LSETH', 'Liquid Staked Ethereum'),
('ORN', 'Orion Protocol'),
('MASK', 'Mask Network'),
('AWG', 'Aruban Florin'),
('NPR', 'Nepalese Rupee'),
('AAVE', 'Aave'),
('MNT', 'Mongolian Tögrög'),
('PRIME', 'Echelon Prime'),
('GBP', 'Pound Sterling'),
('BYN', 'New Belarusian Ruble'),
('PERP', 'Perpetual Protocol'),
('BYR', 'Belarusian Ruble'),
('GBX', 'Penny Sterling'),
('BOND', 'BarnBridge'),
('YFI', 'Yearn Finance'),
('XDR', 'Special Drawing Rights'),
('LQTY', 'Liquity'),
('TIME', 'Chrono.tech'),
('BICO', 'Biconomy'),
('BZD', 'Belize Dollar'),
('MOP', 'Macau Pataca'),
('MONA', 'Monavale'),
('AXL', 'Axelar'),
('AXS', 'Axie Infinity'),
('TRAC', 'OriginTrail'),
('MPL', 'Maple'),
('COMP', 'Compound'),
('WAXL', 'Axelar'),
('HFT', 'Hashflow'),
('WAMPL', 'Wrapped Ampleforth'),
('OOKI', 'Ooki Protocol'),
('DEXT', 'DEXTools'),
('FORTH', 'Ampleforth Governance Token'),
('GHST', 'Aavegotchi'),
('KMF', 'Comorian Franc'),
('MATH', 'MATH'),
('IDEX', 'IDEX'),
('GEL', 'Georgian Lari'),
('AVAX', 'Avalanche'),
('AZN', 'Azerbaijani Manat'),
('UAH', 'Ukrainian Hryvnia'),
('KNC', 'Kyber Network Crystals'),
('ALEPH', 'Aleph.im'),
('GFI', 'Goldfinch'),
('MRO', 'Mauritanian Ouguiya'),
('LPT', 'Livepeer (LPT)'),
('MRU', 'Mauritanian Ouguiya'),
('GODS', 'Gods Unchained'),
('PYG', 'Paraguayan Guaraní'),
('JMD', 'Jamaican Dollar'),
('PYR', 'Vulcan Forged PYR'),
('BTRST', 'Braintrust'),
('SUKU', 'SUKU'),
('DAI', 'DAI'),
('GGP', 'Guernsey Pound'),
('DAR', 'Mines of Dalarnia'),
('FET', 'Fetch.ai'),
('CBETH', 'Coinbase Wrapped Staked ETH'),
('VEF', 'Venezuelan Bolívar Fuerte'),
('ZMK', 'Zambian Kwacha'),
('LRC', 'Loopring'),
('REPV2', 'REPv2'),
('LRD', 'Liberian Dollar'),
('MTL', 'Maltese Lira'),
('VES', 'Venezuelan Bolívar'),
('ZMW', 'Zambian Kwacha'),
('USDT', 'Tether'),
('OXT', 'Orchid Network'),
('DASH', 'Digital Cash'),
('ILS', 'New Israeli Sheqel'),
('ILV', 'Illuvium'),
('GHS', 'Ghanaian Cedi'),
('KPW', 'North Korean Won'),
('MEDIA', 'Media Network'),
('JOD', 'Jordanian Dinar'),
('GUSD', 'Gemini US Dollar'),
('HKD', 'Hong Kong Dollar'),
('LSL', 'Lesotho Loti'),
('KEEP', 'Keep Network'),
('CAD', 'Canadian Dollar'),
('EEK', 'Estonian Kroon'),
('MUR', 'Mauritius Rupee'),
('IMP', 'Isle of Man Pound'),
('GIP', 'Gibraltar Pound'),
('IMX', 'Immutable X'),
('LTC', 'Litecoin'),
('USDC', 'USDC'),
('METIS', 'MetisDAO'),
('XMON', 'XMON'),
('INJ', 'Injective'),
('KRL', 'Kryll'),
('LTL', 'Lithuanian Litas'),
('SAR', 'Saudi Riyal'),
('VGX', 'Voyager Token'),
('MVR', 'Maldivian Rufiyaa'),
('TRIBE', 'Tribe'),
('INR', 'Indian Rupee'),
('INV', 'Inverse Finance'),
('POND', 'Marlin'),
('KRW', 'South Korean Won'),
('JPY', 'Japanese Yen'),
('SBD', 'Solomon Islands Dollar'),
('XLM', 'Stellar'),
('DDX', 'DerivaDAO'),
('LINK', 'Chainlink'),
('MWK', 'Malawian Kwacha'),
('SUPER', 'SuperFarm'),
('POLS', 'Polkastarter'),
('KSM', 'Kusama'),
('FIL', 'Filecoin'),
('POLY', 'Polymath'),
('RNDR', 'Render Token'),
('BAL', 'Balancer'),
('BAM', 'Bosnia-Herzegovina Convertible Mark'),
('GALA', 'Gala'),
('EGP', 'Egyptian Pound'),
('FIS', 'Stafi'),
('RAD', 'Radicle'),
('BAT', 'Basic Attention Token'),
('MXC', 'MXC'),
('NZD', 'New Zealand Dollar'),
('RAI', 'Rai Reflex Index'),
('COTI', 'COTI');